config/routes.rb
Rails.application.routes.draw do
  root to: "trips#index"
  resources :trips, only: %i(create update destroy)
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/trip.rb
class Trip < ApplicationRecord
  validates :state, presence: true
  validates :code, uniqueness: true, presence: true

  before_validation :set_code
  after_validation :trigger_event_publisher
  before_save :print_state
  before_save :trigger_payment

  enum state: {
    created: 'created',
    started: 'started',
    canceled: 'canceled'
  }

  private

  def trigger_event_publisher
    return unless state_changed? || !persisted?

    rabbit = Rabbit.new
    rabbit.publish("Trip n° #{id} has been #{state}")
    rabbit.destroy
  end

  def trigger_payment
    return unless state_changed? || !persisted?

    Payment.bill if created?
    Payment.pay if started?
    Payment.reimburse if canceled?
  end

  def print_state
    return unless state_changed?

    Rails.logger.info state
  end

  def set_code
    return if persisted?

    self.code = generate_code
  end

  def generate_code
    loop do
      new_code = SecureRandom.base58(4)
      break new_code unless Trip.find_by(code: new_code)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  before_action :set_trip, only: %i(update destroy)

  def index
    @trips = Trip.all
  end

  def create
    @trip = Trip.new
    build_notice(@trip.state) if @trip.save
    respond_to(&:js)
  end

  def update
    build_notice(@trip.state) if @trip.started!
    respond_to(&:js)
  end

  def destroy
    build_notice(@trip.state) if @trip.canceled!
    respond_to(&:js)
  end

  private

  def set_trip
    @trip = Trip.find(params[:id])
  end

  def build_notice(state)
    flash[:notice] = "Trip successfully #{state}"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/trips_helper.rb
module TripsHelper
  def trip_text_color(trip)
    'text-danger' if trip.canceled?
  end

  def display_links(trip)
    return if trip.canceled?

    if trip.started?
      link_to 'Cancel', trip, method: :delete, class: 'btn btn-danger', id: "cancel-trip-btn-#{trip.id}", remote: true
    else
      link_to('Start', trip, method: :patch, class: 'btn btn-warning mx-1', id: "start-trip-btn-#{trip.id}", remote: true) +
      link_to('Cancel', trip, method: :delete, class: 'btn btn-danger', id: "cancel-trip-btn-#{trip.id}", remote: true)
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EcoTrip</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_alert.html.erb
<div class="bg-danger text-center p-2">
  Error
</div>

app/views/shared/_notice.html.erb
<div class="bg-success h-100 text-center p-2">
  <%= flash[:notice] %>
</div>

app/views/trips/_trip.html.erb
<li class="list-group-item d-flex justify-content-between <%= trip_text_color(trip) %>" id="trip-li-<%= trip.id %>">
  <div>
    Trip n° <%= trip.id %>
    <span id="state-<%= trip.id %>">(<%= trip.state %>)</span>
  </div>
  <div>
    <%= display_links(trip) %>
  </div>
</li>

app/views/trips/create.js.erb
<% if @trip.errors.any? %>
  document.getElementById('flash').innerHTML = '<%= j render 'shared/alert' %>';
<% else %>
  document.getElementById('flash').innerHTML = '<%= j render 'shared/notice' %>';
  document.getElementById('trip-list').innerHTML += '<%= j render 'trip', trip: @trip %>'
<% end %>

hideFlash(3000);

app/views/trips/destroy.js.erb
<% if @trip.errors.any? %>
  document.getElementById('flash').innerHTML = '<%= j render 'shared/alert' %>';
<% else %>
  document.getElementById('flash').innerHTML = '<%= j render 'shared/notice' %>';
  var startInput = document.getElementById('<%= "start-trip-btn-#{@trip.id}" %>');
  if(startInput){
      startInput.remove();
  }
  document.getElementById('<%= "cancel-trip-btn-#{@trip.id}" %>').remove();
  document.getElementById('<%= "state-#{@trip.id}" %>').innerText = '<%= "(#{@trip.state})" %>';
  document.getElementById('<%= "trip-li-#{@trip.id}" %>').classList.add('text-danger');
<% end %>

hideFlash(3000);

app/views/trips/index.html.erb
<div class="jumbotron jumbotron-fluid position-relative">
  <div class="position-absolute" id="flash"></div>
  <div class="container">
    <h1 class="display-4">Eco Trip</h1>
    <p class="lead">Voyage écologique</p>
  </div>
</div>

<div class="container">
  <ul id="trip-list" class="list-group">
    <%= link_to "Create a Trip", trips_path, method: :post, class: 'btn btn-block btn-primary mb-1', remote: true %>
    <%= render @trips %>
  </ul>
</div>

app/views/trips/update.js.erb
<% if @trip.errors.any? %>
  document.getElementById('flash').innerHTML = '<%= j render 'shared/alert' %>';
<% else %>
  document.getElementById('flash').innerHTML = '<%= j render 'shared/notice' %>';
  document.getElementById('<%= "start-trip-btn-#{@trip.id}" %>').remove();
  document.getElementById('<%= "state-#{@trip.id}" %>').innerText = '<%= "(#{@trip.state})" %>';
<% end %>

hideFlash(3000);